---
version: 2.1
jobs:
  build:
    docker:
      - image: onngawasabi/dotfiles:1.1
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run: make init
      - run: make deploy
      - run: zsh ./etc/test.sh
