[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'navarasu/onedark.nvim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
let g:airline_theme='iceberg'        "I assume you already had this line
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'projekt0n/github-nvim-theme'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" powerline symbols
"let g:airline_left_sep = ''
let g:airline_left_alt_sep = ' '
"let g:airline_right_sep = ''
let g:airline_right_alt_sep = ' '

let g:airline_symbols.branch = ''
let g:airline_symbols.colnr = ' :'
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ' '
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.dirty='⚡'

" Tab
let g:airline#extensions#tabline#enabled = 1
"let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ' '
"let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#right_alt_sep = ' '
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap gs <Cmd>Gdiffsplit<CR><C-w>l
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'akinsho/git-conflict.nvim'

[[plugins]]
repo = 'rbgrouleff/bclose.vim'

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'
depends = ['rbgrouleff/bclose.vim']
hook_add = '''
" open tig with Project root path
nnoremap <Space>t :TigOpenProjectRootDir<CR><C-\><C-n>:set nonumber<CR>i
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
" windowサイズを簡単に変えるためのプラグイン
let g:winresizer_start_key = '<C-e>'

" If you want to cancel and quit window resize mode by `z` (keycode 122)
"let g:winresizer_keycode_cancel = 122
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'delphinus/emcl.nvim'
hook_source = '''
lua << EOF
require("emcl").setup({})
EOF
'''

[[plugins]]
repo = 'tpope/vim-surround'
