[[plugins]]
repo = 'wellle/context.vim'
on_event = 'BufEnter'
hook_add = '''
let g:context_enabled = 0
'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
vim.opt.list = true
require("indent_blankline").setup {
    show_current_context = true,
}
EOF
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
require'colorizer'.setup()
EOF
'''
