[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = 'plenary.nvim'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
require('telescope').setup{
  -- refer to https://github.com/nvim-telescope/telescope.nvim/issues/522
  defaults = {
    initial_mode = "insert",
    file_ignore_patterns = {
      "node_modules/",
      "submodules/",
      ".git/",
      "%.tmp/*",
      "%.jpg",
      "%.jpeg",
      "%.png",
      "%.zip",
      "%.tar",
      "%.tar.gz",
      ".tmp/"
    },
  },
}
EOF

nnoremap <Space>p <cmd>Telescope find_files hidden=true<cr>
nnoremap <Space>d <cmd>Telescope find_files cwd=~/dotfiles<cr>

nnoremap <Space>b <cmd>Telescope buffers<cr>
nnoremap <Space>h <cmd>Telescope help_tags<cr>
nnoremap <Space>g <cmd>Telescope live_grep<cr>

" Lsp
nnoremap gd <Cmd>lua require'telescope.builtin'.lsp_definitions()<CR>
nnoremap gi <Cmd>lua require'telescope.builtin'.lsp_implementations()<CR>
nnoremap gr <Cmd>lua require'telescope.builtin'.lsp_references()<CR>

" Trouble
nnoremap gxd <Cmd>lua require'telescope.builtin'.diagnostics	()<CR>
'''

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
depends = ['telescope.nvim']
on_source = 'telescope.nvim'
hook_source = '''
lua << EOF
require("telescope").load_extension "file_browser"
EOF
" start in folder browser: files=false
nnoremap <Space>f <Cmd>lua require("telescope").extensions.file_browser.file_browser({files=false})<CR>
'''


[[plugins]]
repo = 'akinsho/nvim-toggleterm.lua'
on_source = 'telescope.nvim'
hook_source = '''
lua << EOF
require("toggleterm").setup({
  close_on_exit = true, -- close the terminal window when the process exits
}
)
EOF
'''

[[plugins]]
repo = 'onnga-wasabi/telescope-makefile'
depends = ['telescope.nvim', 'nvim-toggleterm.lua']
on_source = 'telescope.nvim'
hook_source = '''
lua << EOF
require('telescope').load_extension('make')
require('telescope-makefile').setup({
  toggle_term = {
    cmd = 'make',
    direction = 'float',
    close_on_exit = true,
  },
})
EOF
nnoremap <Space>m <Cmd>Telescope make<CR>

augroup close_toggleterm
  autocmd!
  autocmd FileType toggleterm tnoremap <buffer>, <Cmd>:q<CR>
  autocmd FileType toggleterm nnoremap <buffer>, <Cmd>:q<CR>
augroup END
'''
